version: '3'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ../..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:db
  db:
    env_file: 
      - .env
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ../../data/mysql:/var/lib/mysql